spring.application.name=EcoCheck2026
server.servlet.context-path=/ecocheck

#Database config
spring.datasource.url=jdbc:mysql://localhost:3306/ecoCheckCMJD2026?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=ett25304
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA Configs / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#REMOVED the old dialect line completely. Hibernate 7 automatically detects MySQL from your connection URL!
